### ISSUE TITLE
Problem Maximum call stack size exceeded on server

### ISSUE THREAD

**Issue by vallettea** [anthill/city-core#91]
```
~/city-core ❯❯❯ forever server.js                                                                                                                               ⏎
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
starting in mode dev
Server running on 9000

/home/queenant/city-core/node_modules/socket.io/node_modules/engine.io/lib/socket.js:338
      this.sentCallbackFn.push.apply(this.sentCallbackFn, this.packetsFn);
                               ^
RangeError: Maximum call stack size exceeded
    at Socket.flush (/home/queenant/city-core/node_modules/socket.io/node_modules/engine.io/lib/socket.js:338:32)
    at WebSocket.EventEmitter.emit (events.js:117:20)
    at /home/queenant/city-core/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:94:14
    at afterWrite (_stream_writable.js:274:3)
    at onwrite (_stream_writable.js:266:7)
    at Socket.WritableState.onwrite (_stream_writable.js:97:5)
    at Object.afterWrite (net.js:728:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
starting in mode dev
Server running on 9000
```

**Comment by DavidBruant** [comment]
Internal socket.io error... hmm... In #28, I suggest getting rid of socket.io. No better idea at this point.

**Comment by Cristy94** [comment]
I got the same issue, with call stack size exceeded when calling 
`this.sentCallbackFn.push.apply(this.sentCallbackFn, this.packetsFn);`

How did you fix your problem?
